# Generated by Django 4.2.16 on 2024-10-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_user_myrequests_user_friendrequests_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='cat.png', max_length=255, null=True),
        ),
    ]
