# Generated by Django 4.2.16 on 2024-11-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_resetpasswordmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otpTwoFA',
        ),
        migrations.AddField(
            model_name='user',
            name='TwoFACode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='TwoFA_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
