# Generated by Django 4.2.16 on 2024-11-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0009_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authProvider',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isAuth',
            field=models.BooleanField(default=False),
        ),
    ]
