# Generated by Django 4.2.16 on 2024-11-20 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0010_user_authprovider_user_isauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match_data', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='userStatsId',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
