# Generated by Django 4.2.16 on 2024-11-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0014_user_isonline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isOnline',
        ),
    ]
