FROM debian:bookworm

RUN apt-get update && apt-get install -y nginx
COPY . /home
COPY ./default.conf /etc/nginx/sites-available/default
COPY ./ssl /etc/nginx/ssl

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]