version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - network
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./frontend
    container_name: nginx_service
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - db

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
    # networks:
    #   - elk

networks:
  network:
    driver: bridge

volumes:
  db_data: