# Generated by Django 4.2.16 on 2024-11-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
