# Generated by Django 4.2.16 on 2024-11-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='../images/cat.png', max_length=255, null=True),
        ),
    ]
