# Generated by Django 4.2.16 on 2024-11-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0011_matchhistory_remove_user_userstatsid_delete_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
