# Generated by Django 4.2.16 on 2024-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0012_user_loses_user_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
