version: '3.8'

services:
  elasticsearch:
    image: localbuild/elasticsearch:7.14.1
    build:
      context: elasticsearch/
      args:
         elk_version: 7.14.1
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTIC_PASSWORD: aouchaadtest
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.2.0
  #   container_name: logstash
  #   environment:
  #     - ELASTIC_USERNAME=elastic
  #     - ELASTIC_PASSWORD=aouchaadtest
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline
  #   ports:
  #     - "5044:5044"
  #     - "9600:9600"
  #   depends_on:
  #     - elasticsearch
  #     - kibana
  #   networks:
  #     - elk

  # kibana:
  #   image: kibana
  #   container_name: kibana
  #   build:
  #     context: ./kibana
  #     dockerfile: Dockerfile
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - ELASTICSEARCH_USERNAME=elastic
  #     - ELASTICSEARCH_PASSWORD=aouchaadtest
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - elk

  logstash:
    image: localbuild/logstash:7.14.1
    build:
      context: logstash/
      args:
         elk_version: 7.14.1
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: localbuild/kibana:7.14.1
    build:
      context: kibana/
      args:
         elk_version: 7.14.1
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD", "curl --silent --fail localhost:5061/status || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
  elasticsearch:


networks:
  elk:
    name: elk
    driver: bridge
  