version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=aouchaadtest
    volumes:
      - ./setup_elasticsearch.sh:/usr/share/elasticsearch/setup_elasticsearch.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
    networks:
      - elk
    ports:
      - "9200:9200"
    command: ["/bin/bash", "-c", "/usr/share/elasticsearch/setup_elasticsearch.sh && bin/elasticsearch"]

  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.0
    container_name: logstash
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=aouchaadtest
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=aouchaadtest
    ports:
      - "5601:5601"
    networks:
      - elk
    volumes:
      - ./kibana/setup_kibana.sh:/usr/share/kibana/setup_kibana.sh
    command: ["/bin/bash", "-c", "/usr/share/kibana/setup_kibana.sh && bin/kibana"]

volumes:
  esdata:
    driver: local


networks:
  elk:
    driver: bridge