POST http://localhost:8000/api/users/login
Content-Type: application/json

{ "email": "aminnne@gmail.com", "password": "Pass1234"}

###
POST http://localhost:8000/api/users/register/
Content-Type: application/json

{ "username": "z", "email": "aminnne@gmail.com" ,"password": "z", "passwordConfirmation" : "z"}

###
POST http://localhost:8000/api/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI3OTY2NTE2LCJpYXQiOjE3Mjc4ODAxMTUsImp0aSI6IjQyM2ZlZjRlMTM1ODQ0ODk4MGJkMmU3YWRkZGY3ZGJiIiwidXNlcl9pZCI6MX0.gFTTOvE3ooXGduhgl0jczdRsggY6UK5dtKZi85y1Bsg

###
PUT http://localhost:8000/api/users/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwNDMxMTMxLCJpYXQiOjE3MzAzNDQ3MzEsImp0aSI6IjQzMmRhOTc2MzQ5YTRmMzZhY2U2MDA5OGQyM2Y0MTY2IiwidXNlcl9pZCI6M30.klEXwJjiVxibQdK434gcLO0zbDHY7O0fAsvcg_xTxYU

{ "username": "wervwerverv"}

###
DELETE  http://localhost:8000/api/users/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI3ODc2NDYxLCJpYXQiOjE3Mjc3OTAwNjEsImp0aSI6IjM4MDBlNTA4NzRkODRiZmI4NDdlYzhmOWI2ZWUxOGE1IiwidXNlcl9pZCI6MX0.NgyIT4_FjZdmSWWHBMZzUOJku0C9WkhDcmALZRpKgbo
###
POST  http://localhost:8000/api/users/refresh
Content-Type: application/json

###
GET http://localhost:8000/api/oauth/login/
Content-Type: application/json